mob writing 



ASSIGMENT 01
MOB Writing Group Task












Team Members:
Task	Name	Student ID
Summary	Aksh	12148805
Question 01	Malith	12193993
Question 02	Jai	12196243
Question 03	Dipanjit	12159732
Editing	Dilsha	12195171
Contents

ASSIGMENT 01	1
MOB Writing Group Task	1
Summary	3
Communication challenges that global virtual Teams face	4
Benefits that delivery in teams offers for the development of ICT systems.	5
Diversity in the workplace	5
The diversity types in workplace	5
Benefits of diversity in the workplace	5
Recommendation for global virtual team members to improve their communication	6

 
Summary
“Communicate Through the Roof”: A Case Study Analysis of the Communicative Regulations and Resources of an Effective Global Virtual Team. They members move out because of several factors like time, distance, and culture as well. Moreover, other factors related to this factor are conflicts, and potentially divided into sub-groups. To overcome this problem the members from the team focus on ritual rites by their software development process and reduce their communication problems.
 When they move away from each other by time and distance factor it is only due to facing hazard with lack of trust in relationships and they cannot let go with some conflict. It is highly recommended for working as a team that is independent and free to share goals with others. When they are doing tasks in a group it will be easier to do because different people have various skills to do the same work. However, working in a group is meaningless to external support and recognition. A GVT has high quality when compared with co-located group. The main advantage of GVT is that some scholars term them as “the norm for business and governments around the world”. Then, By GVTs we can put right people in right position all over the globe.
 On the other hand, GVTs have some demerits according to division by time and culture are highly complaint for working together. English -Luck et al. noticed that “interdependent high-tech work, often using technologically mediated communication, requires a great amount of trust". Some consequences can mitigate the problem by geographically various. Structuration theory also indicates that group of possess agency. This refers to the fact that everyone can do work self-reflectively. There are three methods of GVT: the first one is Research Setting, second is Participants, and last one is Data Collection.
 By the sprint planning meeting, rituals were demolished that encouraged all members to speak and be heard. To conclude, the aim of this research was to get results from the bottom of interactions of one fixed team, opposite side this applicability of the finding to different situation.it is based on fully successful co-located team.
 
Communication challenges that global virtual Teams face
 According to this article, there are several communication challenges which would be affected by global virtual team's face. First one is the distant of communication. Research suggests that there is better understanding in face-to-face communication. It makes both sides combatable as well as it is the Bestway to solve if there is a problem. Another good example for proof that face-to-face communication is the best form of communication for establishing relationships and trust, Court. That is why in any country, in case of any violation of the law, the culprit is discussed in court as wrong or right. in the Interviews also, using this communication method and it is easy to get an idea about the applicant.
 in addition to that, another main provocation is the time difference. Since 2019, when the corona pandemic begun Most people, even the school children's must do their profession and studies via the online mode. Simply put, “ZOOM”. In this case think, if you are in Asia country, and you must join to the meeting in your office. In this case, Problems arise due to time lag. It is comfortable for one person, but it is not for another. Therefor time can become a source of challenge in global virtual teams.
Culture is also a characteristic that complicate and make challenging working together. Diverse cultures have different languages, and their speaking accent is different from one another. In this case it is too much hard to understand and keep relationship in each other. If you are doing a teamwork with different culture mates, that would be a big challenge.
 
Benefits that delivery in teams offers for the development of ICT systems.
Diversity in the workplace is the acceptance of the employees of all backgrounds. A workplace where people from diverse cultures meet is an important asset as it Acknowledges the individual potential of each employee and the firmness they bring. Valuing the differences of others is what makes us, and this can be the secret for a successful workplace with a fair work culture.
Diversity in the workplace 
Workplace diversity means respecting and valuing the skills and cultural differences that each person brings into the workspace. A diverse workplace is a comprehensive atmosphere that gives equal rights and opportunities for all workers, regardless of gender, color, age, ethnicity, religion, and so on.
There must be a law for workplaces to provide equal opportunity to their employees, as well as to create a workplace free from discrimination includes valuing workplace diversity and ensuring that a workplace is free from racial and sexual harassment, and so on.
The diversity types in workplace 
It is important to recognize the types of diversity and to provide different paths to affirm that you as an employer, or employee who are contributing toward a more diverse and inclusive workplace. Employing crew with barriers to employment and treating them fairly is one of the ways employers can attract a more diverse workplace and diversify the workplace
Identifying and addressing any bias when it comes to offering a job. The hiring managers must be aware of the qualities and assets the applicant’s background can bring to the company and ensure they are allowing for a fair recruitment process. Which leads to the belief that you are an equal-rights employer.
Value the skills that employees are providing and making sure to utilize these to help broaden your market. This Allows flexible work options and provide the opportunity to both women and men. It also includes the feeling that they are being heard and someone is there at their back
Benefits of diversity in the workplace 
A diverse workplace allows for more ideas as many people with different potentials lead to different ideas, so we get to know about pros and cons. In other words, the chances of failure are less. Also, many cultures within the workplace allows companies to deal with the different issues within a global marketplace which can lead to better relation and ties which will lead to a positive reputation of the workplace and increasing the marketing opportunities 
Achieving workplace diversity means you are bringing out the best in your employees and allowing them to reach their full potential. By doing so, your workplace benefits as it encourages a more varied and innovative talent pool.
 
Recommendation for global virtual team members to improve their communication

Global virtual team members are defined separation by distance, time and culture are not same. But that does not mean they do not work together. The first thing is trust and establishing is if they trust on another member then they start communication and gave some benefits to each other they learn and take some more knowledge about another religion   another culture and another country and can improve their communication skills when they communicate each other.
In the other hand if they are not in a same room and not in same time zone. Today we have smart technologies. In this situation they start communicating by virtual online apps like zoom, skype and so on. They create virtual teams from global. It does not mean the online meeting is only just a communication. Becoming independent of face-to-face meeting does not mean that they should not meet face to face any longer, it means they have real choice and the confidence that you can achieve high performance in the virtual team.


